version: '3'

services: 
  docker-mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=test
      - MYSQL_PASSWORD=admin
  bbsn-server:
    container_name: bbsn-server
    image: server-docker
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - 8080
    depends_on:
      - docker-mysql